services:
  - type: web
    name: agropulse
    runtime: python
    buildCommand: ""
    startCommand: python3 server.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.11.6"
